apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vl1ytcfz7-nodejs
  janus-idp.io/tekton: vl1ytcfz7-nodejs
  backstage.io/kubernetes-id: vl1ytcfz7-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: vl1ytcfz7-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
